/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as PracticeLevelIdIndexRouteImport } from './routes/practice/$levelId/index'
import { Route as PracticeLevelIdSectionIdRouteImport } from './routes/practice/$levelId/$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeLevelIdIndexRoute = PracticeLevelIdIndexRouteImport.update({
  id: '/practice/$levelId/',
  path: '/practice/$levelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeLevelIdSectionIdRoute =
  PracticeLevelIdSectionIdRouteImport.update({
    id: '/practice/$levelId/$sectionId',
    path: '/practice/$levelId/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/practice/': typeof PracticeIndexRoute
  '/practice/$levelId/$sectionId': typeof PracticeLevelIdSectionIdRoute
  '/practice/$levelId/': typeof PracticeLevelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/practice': typeof PracticeIndexRoute
  '/practice/$levelId/$sectionId': typeof PracticeLevelIdSectionIdRoute
  '/practice/$levelId': typeof PracticeLevelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/practice/': typeof PracticeIndexRoute
  '/practice/$levelId/$sectionId': typeof PracticeLevelIdSectionIdRoute
  '/practice/$levelId/': typeof PracticeLevelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/practice/'
    | '/practice/$levelId/$sectionId'
    | '/practice/$levelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/practice'
    | '/practice/$levelId/$sectionId'
    | '/practice/$levelId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/practice/'
    | '/practice/$levelId/$sectionId'
    | '/practice/$levelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  PracticeLevelIdSectionIdRoute: typeof PracticeLevelIdSectionIdRoute
  PracticeLevelIdIndexRoute: typeof PracticeLevelIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$levelId/': {
      id: '/practice/$levelId/'
      path: '/practice/$levelId'
      fullPath: '/practice/$levelId/'
      preLoaderRoute: typeof PracticeLevelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$levelId/$sectionId': {
      id: '/practice/$levelId/$sectionId'
      path: '/practice/$levelId/$sectionId'
      fullPath: '/practice/$levelId/$sectionId'
      preLoaderRoute: typeof PracticeLevelIdSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  PracticeLevelIdSectionIdRoute: PracticeLevelIdSectionIdRoute,
  PracticeLevelIdIndexRoute: PracticeLevelIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
